version: "3.7"
services:
    frontend:
        build:
            context: .
            dockerfile: frontend/.devcontainer/Dockerfile
        command: sleep infinity
        ports:
            - 3000:3000
        volumes:
            - ./:/app
    backend:
        build:
            context: .
            dockerfile: backend/.devcontainer/Dockerfile
        command: sleep infinity
        ports:
            - 3001:3000
        volumes:
            - ./:/app
    db:
        image: mysql/mysql-server:8.0
        env_file:
            - .env.development
        command: mysqld --default_authentication_plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
        ports:
            - '3306:3306'
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
